/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connection.ConexaoBD;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Luisw7
 */
public class EntradaSaida extends javax.swing.JFrame {
    ConexaoBD conex = new ConexaoBD();
    String id;
    Autenticacao au = new Autenticacao();
    /**
     * Creates new form EntradaSaida
     */
    public EntradaSaida(){
        initComponents();
        JOptionPane.showMessageDialog(null,id);
    }
    
    public void setID(String id){
        this.id = au.getTipo();
    }
    public String getID(){
        return id;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Entrada");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Saida");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Deseja Registrar a entrada ou saída?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(59, 59, 59))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        conex.conexao();
        String mes = new java.text.SimpleDateFormat("MM").format(new java.util.Date());;
        String tipo = "e";
        String a = "\"";
        
        if (mes.equals("01")) mes = "janeiro";
        if (mes.equals("02")) mes = "fevereiro";
        if (mes.equals("03")) mes = "marco";
        if (mes.equals("04")) mes = "abril";
        if (mes.equals("05")) mes = "maio";
        if (mes.equals("06")) mes = "junho";
        if (mes.equals("07")) mes = "julho";
        if (mes.equals("08")) mes = "agosto";
        if (mes.equals("09")) mes = "setembro";
        if (mes.equals("10")) mes = "outubro";
        if (mes.equals("11")) mes = "novembro";
        if (mes.equals("12")) mes = "dezembro";
        
        String registro = " UPDATE";
        registro +=' ';
        registro +=mes;
        registro +=' ';
        registro +="SET";
        registro +=' ';
        registro +=a;
        registro += new java.text.SimpleDateFormat("dd").format(new java.util.Date());
        registro +=' ';
        registro +=tipo;
        registro +=a;
        registro +=' ';
        registro +='=';
        registro +=' ';
        registro +='1';
        registro +=' ';
        registro +="WHERE";
        registro +=' ';
        registro +=a;
        registro +=mes;
        registro +=a;
        registro +='.';
        registro +=a;
        registro +="id";
        registro +=a;
        registro +=' ';
        registro +='=';
        registro +=id;
        
        try {
            PreparedStatement pst = conex.con.prepareStatement(registro);
            pst.execute();
            JOptionPane.showMessageDialog(null,registro);
            PontoRegistrado p = new PontoRegistrado();
            p.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao realizar instrução:\n"+ex);
            conex.desconecta();
            //Logger.getLogger(EntradaSaida.class.getName()).log(Level.SEVERE, null, ex);
        }
        //JOptionPane.showMessageDialog(null,registro);
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        conex.conexao();
        String mes = new java.text.SimpleDateFormat("MM").format(new java.util.Date());;
        String tipo = "s";
        String a = "\"";
        
        if (mes.equals("01")) mes = "janeiro";
        if (mes.equals("02")) mes = "fevereiro";
        if (mes.equals("03")) mes = "marco";
        if (mes.equals("04")) mes = "abril";
        if (mes.equals("05")) mes = "maio";
        if (mes.equals("06")) mes = "junho";
        if (mes.equals("07")) mes = "julho";
        if (mes.equals("08")) mes = "agosto";
        if (mes.equals("09")) mes = "setembro";
        if (mes.equals("10")) mes = "outubro";
        if (mes.equals("11")) mes = "novembro";
        if (mes.equals("12")) mes = "dezembro";
        
        String registro = " UPDATE";
        registro +=' ';
        registro +=mes;
        registro +=' ';
        registro +="SET";
        registro +=' ';
        registro +=a;
        registro += new java.text.SimpleDateFormat("dd").format(new java.util.Date());
        registro +=' ';
        registro +=tipo;
        registro +=a;
        registro +=' ';
        registro +='=';
        registro +=' ';
        registro +='1';
        registro +=' ';
        registro +="WHERE";
        registro +=' ';
        registro +=a;
        registro +=mes;
        registro +=a;
        registro +='.';
        registro +=a;
        registro +="id";
        registro +=a;
        registro +=' ';
        registro +='=';
        registro +=id;
        
        try {
            PreparedStatement pst = conex.con.prepareStatement(registro);
            pst.execute();
            JOptionPane.showMessageDialog(null,registro);
            PontoRegistrado p = new PontoRegistrado();
            p.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao realizar instrução:\n"+registro);
            conex.desconecta();
            //Logger.getLogger(EntradaSaida.class.getName()).log(Level.SEVERE, null, ex);
        }
        //JOptionPane.showMessageDialog(null,registro);
        
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntradaSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntradaSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntradaSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntradaSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntradaSaida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
